# Generated by Django 6.0.3 on 2026-03-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentsequence_payment_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('stripe', 'Tarjeta de credito/debito'), ('transfer', 'Transferencia bancaria'), ('cash', 'Efectivo')], default='stripe', max_length=20),
        ),
    ]
