# Generated by Django 6.0.3 on 2026-03-20 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('seccion', models.CharField(choices=[('terraza', 'Terraza Principal'), ('arte', 'Galería de Arte'), ('vip', 'Salón VIP'), ('reuniones', 'Sala de Reuniones'), ('bar', 'La Barra'), ('puros', 'Terraza Puros'), ('musica', 'Música en Vivo')], default='terraza', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('creada_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Galería de Fotos',
                'ordering': ['seccion', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='campanas/')),
                ('tipo', models.CharField(choices=[('banner', 'Banner Principal'), ('popup', 'Popup'), ('destacado', 'Sección Destacada')], default='banner', max_length=20)),
                ('url_destino', models.CharField(blank=True, help_text='URL al hacer click', max_length=300)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creada_at', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-creada_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Creación'), ('editar', 'Edición'), ('eliminar', 'Eliminación'), ('precio', 'Cambio de precio'), ('stock', 'Cambio de stock'), ('oferta', 'Oferta creada'), ('campana', 'Campaña creada')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objeto_nombre', models.CharField(blank=True, max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento %')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('creada_at', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-creada_at'],
            },
        ),
    ]
