# Generated by Django 6.0.3 on 2026-03-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_galeriafoto_external_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campana',
            options={'ordering': ['-creada_at'], 'verbose_name': 'Campana', 'verbose_name_plural': 'Campanas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='galeriafoto',
            options={'ordering': ['seccion', 'orden'], 'verbose_name': 'Foto de Galeria', 'verbose_name_plural': 'Galeria de Fotos'},
        ),
        migrations.AlterField(
            model_name='campana',
            name='tipo',
            field=models.CharField(choices=[('banner', 'Banner Principal'), ('popup', 'Popup'), ('destacado', 'Seccion Destacada')], default='banner', max_length=20),
        ),
        migrations.AlterField(
            model_name='galeriafoto',
            name='seccion',
            field=models.CharField(choices=[('terraza', 'Terraza Principal'), ('arte', 'Galeria de Arte'), ('vip', 'Salon VIP'), ('reuniones', 'Sala de Reuniones'), ('bar', 'La Barra'), ('puros', 'Terraza Puros'), ('musica', 'Musica en Vivo')], default='terraza', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='accion',
            field=models.CharField(choices=[('crear', 'Creacion'), ('editar', 'Edicion'), ('eliminar', 'Eliminacion'), ('precio', 'Cambio de precio'), ('stock', 'Cambio de stock'), ('oferta', 'Oferta creada'), ('campana', 'Campana creada')], max_length=20),
        ),
    ]
