# Generated by Django 6.0.3 on 2026-03-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('zona', models.CharField(choices=[('salon', 'Salón Principal'), ('terraza', 'Terraza'), ('vip', 'Salón VIP'), ('barra', 'Barra')], default='salon', max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('activa', models.BooleanField(default=True)),
                ('pos_x', models.PositiveIntegerField(default=0, help_text='Posición X en el layout')),
                ('pos_y', models.PositiveIntegerField(default=0, help_text='Posición Y en el layout')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['zona', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En Proceso'), ('lista', 'Lista para servir'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='abierta', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('num_comensales', models.PositiveIntegerField(default=1)),
                ('creada_at', models.DateTimeField(auto_now_add=True)),
                ('actualizada_at', models.DateTimeField(auto_now=True)),
                ('cerrada_at', models.DateTimeField(blank=True, null=True)),
                ('garzon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='comandas.mesa')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-creada_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_item', models.CharField(max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Ej: sin cebolla, término medio')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comandas.comanda')),
                ('item_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.itemmenu')),
            ],
            options={
                'ordering': ['creado_at'],
            },
        ),
        migrations.CreateModel(
            name='PerfilGarzon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('zona_asignada', models.CharField(blank=True, choices=[('salon', 'Salón Principal'), ('terraza', 'Terraza'), ('vip', 'Salón VIP'), ('barra', 'Barra')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='garzones/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_garzon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Garzón',
                'verbose_name_plural': 'Perfiles de Garzones',
            },
        ),
    ]
