# Generated by Django 6.0.3 on 2026-04-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_productive_comandas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcomanda',
            options={'ordering': ['creado_at'], 'verbose_name': 'Item de comanda', 'verbose_name_plural': 'Items de comanda'},
        ),
        migrations.AlterModelOptions(
            name='perfilgarzon',
            options={'verbose_name': 'Perfil de garzon', 'verbose_name_plural': 'Perfiles de garzones'},
        ),
        migrations.AlterField(
            model_name='itemcomanda',
            name='notas',
            field=models.TextField(blank=True, help_text='Ej: sin cebolla, termino medio'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='pos_x',
            field=models.PositiveIntegerField(default=0, help_text='Posicion X en el layout'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='pos_y',
            field=models.PositiveIntegerField(default=0, help_text='Posicion Y en el layout'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='zona',
            field=models.CharField(choices=[('salon', 'Salon Principal'), ('terraza', 'Terraza'), ('vip', 'Salon VIP'), ('barra', 'Barra')], default='salon', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilgarzon',
            name='zona_asignada',
            field=models.CharField(blank=True, choices=[('salon', 'Salon Principal'), ('terraza', 'Terraza'), ('vip', 'Salon VIP'), ('barra', 'Barra')], max_length=20),
        ),
    ]
