# Generated by Django 6.0.3 on 2026-03-22 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comandas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente autorización'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('solicitada_at', models.DateTimeField(auto_now_add=True)),
                ('autorizada_at', models.DateTimeField(blank=True, null=True)),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apertura de Caja',
                'verbose_name_plural': 'Aperturas de Caja',
                'ordering': ['-solicitada_at'],
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_efectivo', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_tarjeta_credito', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_tarjeta_debito', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_transferencia', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_propinas', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente autorización'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('solicitado_at', models.DateTimeField(auto_now_add=True)),
                ('autorizado_at', models.DateTimeField(blank=True, null=True)),
                ('apertura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre', to='caja.aperturacaja')),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_autorizados', to=settings.AUTH_USER_MODEL)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-solicitado_at'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta Crédito (Visa/Mastercard)'), ('tarjeta_debito', 'Tarjeta Débito'), ('transferencia', 'Transferencia Bancaria')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('propina', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('ultimos_4', models.CharField(blank=True, max_length=4)),
                ('notas', models.TextField(blank=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('aprobado_at', models.DateTimeField(blank=True, null=True)),
                ('apertura_caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='caja.aperturacaja')),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('comanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='comandas.comanda')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-creado_at'],
            },
        ),
        migrations.CreateModel(
            name='PerfilCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('cajero', 'Cajero'), ('tesorero', 'Tesorero')], default='cajero', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Caja',
                'verbose_name_plural': 'Perfiles de Caja',
            },
        ),
    ]
