# Generated by Django 6.0.3 on 2026-03-23 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia de Transaccion',
            },
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='notas_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='diferencia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='notas_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aperturacaja',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente autorizacion'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente autorizacion'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta Credito (Visa/Mastercard)'), ('tarjeta_debito', 'Tarjeta Debito'), ('transferencia', 'Transferencia Bancaria')], max_length=20),
        ),
        migrations.CreateModel(
            name='Anulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('monto_anulado', models.DecimalField(decimal_places=0, max_digits=12)),
                ('creada_at', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anulaciones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anulacion', to='caja.pago')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anulaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anulacion',
                'verbose_name_plural': 'Anulaciones',
                'ordering': ['-creada_at'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaccion', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('tipo', models.CharField(choices=[('apertura_caja', 'Apertura de Caja'), ('rechazo_apertura', 'Rechazo de Apertura'), ('cierre_caja', 'Cierre de Caja'), ('pago', 'Pago'), ('anulacion', 'Anulacion'), ('reversa', 'Reversa'), ('transferencia', 'Transferencia Autorizada'), ('rechazo_transferencia', 'Rechazo de Transferencia')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('descripcion', models.TextField()),
                ('referencia_modelo', models.CharField(blank=True, max_length=50)),
                ('referencia_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('apertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='caja.aperturacaja')),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaccion de Caja',
                'verbose_name_plural': 'Transacciones de Caja',
                'ordering': ['-fecha'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
