# Generated by Django 6.0.3 on 2026-03-22 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('almuerzo', 'Menú Almuerzo'), ('cena', 'Menú Cena'), ('terraza', 'Menú Terraza'), ('vinos', 'Carta de Vinos'), ('licores', 'Licores & Whiskies')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Menú',
                'verbose_name_plural': 'Categorías de Menú',
                'ordering': ['tipo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('disponible', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('anno', models.CharField(blank=True, max_length=10, verbose_name='Año')),
                ('bodega', models.CharField(blank=True, max_length=100, verbose_name='Bodega/Marca')),
                ('origen', models.CharField(blank=True, max_length=100, verbose_name='Origen/Valle')),
                ('cepa', models.CharField(blank=True, max_length=100, verbose_name='Cepa/Tipo')),
                ('graduacion', models.CharField(blank=True, max_length=20, verbose_name='Graduación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.categoriamenu')),
            ],
            options={
                'verbose_name': 'Item de Menú',
                'verbose_name_plural': 'Items de Menú',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
