# Generated by Django 6.0.3 on 2026-03-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_itemmenu_external_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamenu',
            options={'ordering': ['tipo', 'orden'], 'verbose_name': 'Categoria de Menu', 'verbose_name_plural': 'Categorias de Menu'},
        ),
        migrations.AlterModelOptions(
            name='itemmenu',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Item de Menu', 'verbose_name_plural': 'Items de Menu'},
        ),
        migrations.AlterField(
            model_name='categoriamenu',
            name='tipo',
            field=models.CharField(choices=[('desayuno', 'Menu Desayuno'), ('brunch', 'Brunch y Once'), ('almuerzo', 'Menu Almuerzo'), ('cena', 'Menu Cena'), ('terraza', 'Menu Terraza'), ('vinos', 'Carta de Vinos'), ('licores', 'Licores y Whiskies'), ('cocteles', 'Cocteles'), ('catering', 'Catering y Eventos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='anno',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='graduacion',
            field=models.CharField(blank=True, max_length=20, verbose_name='Graduacion'),
        ),
    ]
