# Generated by Django 6.0.3 on 2026-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_seed_additional_service_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamenu',
            name='tipo',
            field=models.CharField(choices=[('desayuno', 'Menu Desayuno'), ('brunch', 'Brunch y Once'), ('almuerzo', 'Menu Almuerzo'), ('postres', 'Postres'), ('infantil', 'Menu Infantil Dia'), ('te_cafe', 'Te - Cafe e Infusiones'), ('bebidas', 'Bebidas y Cervezas'), ('llevar', 'Para Llevar y Boutique'), ('cena', 'Menu Cena'), ('terraza', 'Menu Terraza'), ('vinos', 'Carta de Vinos'), ('licores', 'Licores y Whiskies'), ('cocteles', 'Cocteles'), ('catering', 'Catering y Eventos')], max_length=20),
        ),
    ]
