# Generated by Django 6.0.3 on 2026-03-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
    ]
